[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "sd_encoder"
description = "Rust-accelerated structured data encoder for LLM token compression"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
authors = [
    { name = "Yanick Andrade", email = "info@clm-lang.com" },
]
keywords = [
  "Natural Language Compression",
  "LLM Compressor",
  "Compressed Language Model",
  "CLM",
  "NLP",
  "Text Compression",
  "Structure Data Compression",
  "SDEncoder"
]
readme = "README.md"
dynamic = ["version"]

[dependency-groups]
dev = ["twine>=6.1.0"]

[tool.maturin]
python-source = "python"
module-name = "sd_encoder._sd_encoder"
bindings = 'pyo3'
editable-profile = 'dev'
