from collections.abc import Mapping, Sequence
from typing import Any, ClassVar

class FieldImportance:
    LOW: ClassVar[FieldImportance]
    MEDIUM: ClassVar[FieldImportance]
    HIGH: ClassVar[FieldImportance]
    CRITICAL: ClassVar[FieldImportance]

    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: FieldImportance) -> bool: ...
    def __le__(self, other: FieldImportance) -> bool: ...
    def __gt__(self, other: FieldImportance) -> bool: ...
    def __ge__(self, other: FieldImportance) -> bool: ...
    def __index__(self) -> int: ...
    def __hash__(self) -> int: ...

class CLMOutput:
    @property
    def compressed(self) -> str: ...
    @property
    def original(self) -> Any: ...
    @property
    def component(self) -> str: ...
    @property
    def metadata(self) -> dict[str, str] | None: ...
    def n_tokens(self) -> int: ...
    def c_tokens(self) -> int: ...
    def compression_ratio(self) -> float: ...
    def validate_compression_ratio(self) -> CLMOutput: ...
    def validate_compressed(self) -> CLMOutput: ...

class SDCompressionConfig:
    def __init__(
        self,
        required_fields: Sequence[str] | None = None,
        auto_detect: bool | None = None,
        drop_non_required_fields: bool | None = None,
        importance_threshold: FieldImportance | None = None,
        field_importance: Mapping[str, FieldImportance] | None = None,
        excluded_fields: Sequence[str] | None = None,
        max_truncation_length: int | None = None,
        preserve_structure: bool | None = None,
        max_truncation_mapping: Mapping[str, int] | None = None,
        default_fields_order: Sequence[str] | None = None,
    ) -> None: ...
    @property
    def required_fields(self) -> list[str] | None: ...
    @property
    def auto_detect(self) -> bool | None: ...
    @property
    def preserve_structure(self) -> bool | None: ...
    @property
    def drop_non_required_fields(self) -> bool | None: ...
    @property
    def max_truncation_length(self) -> int | None: ...
    @property
    def excluded_fields(self) -> list[str] | None: ...
    @property
    def default_fields_order(self) -> list[str]: ...
    @property
    def field_importance(self) -> dict[str, FieldImportance] | None: ...
    @property
    def max_truncation_mapping(self) -> dict[str, int] | None: ...

class SDEncoderV2:
    def __init__(self, config: SDCompressionConfig, delimiter: str = ",") -> None: ...
    def encode(self, data: Any) -> CLMOutput: ...
    def encode_validated(self, data: Any) -> CLMOutput: ...
    @property
    def delimiter(self) -> str: ...
